import { Request } from 'express';

import DBConn from './conn';
import tables from '../config/tables';

export default class Auth {

    /**
     * Checks user's auth_web_token against the one generated by the emulator
     * @param req Express Request object
     * @returns Authenticity status
     */
    static async isAuth(req: Request) {
        const body = req.body || {};

        const authToken = body['AuthToken'];
        const accountId = body["AID"];
        
        if (!authToken || !accountId)
            return false;

        try {
            const results = await DBConn.query(`
                SELECT account_id 
                FROM ${tables.login} 
                WHERE (account_id = ${accountId}
                    AND web_auth_token = '${authToken}'
                    AND web_auth_token_enabled = '1')
            `);

            return results.length > 0;

        } catch (error) {
            console.error(error);
            return false;
        }
    }

    /**
     * Check if user is guildmaster of guild
     * @param req Request object
     * @returns User is guildmaster
     */
    static async isGuildMaster(req: Request) {
        const body = req.body || {};
        
        const accountId = body["AID"];
        const guildId = body['GDID'];

        if (!accountId || !guildId) {
            return false;
        }

        try {
            const results = await DBConn.query(`
                SELECT account_id
                FROM ${tables.login} 
                LEFT JOIN using (char_id)
                WHERE ${tables.login}.account_id = ${accountId}
                    AND ${tables.login}.guild_id = ${guildId}
            `);

            return results.length > 0;
        } catch(error) {
            console.error(error);
        }
    }
}