import { Request } from 'express';

import DBConn from './conn';
import tables from '../config/tables';
import {escape as esc} from 'mysql';

export default class Auth {

    /**
     * Checks user's auth_web_token against the one generated by the emulator
     * @param req Express Request object
     * @returns Authenticity status
     */
    static async isAuth(req: Request) {
        const body = req.body || {};

        const authToken = body['AuthToken'];
        const accountId = body["AID"];
        
        if (!authToken || !accountId)
            return false;

        try {
            const query = `
            SELECT \`account_id\` 
            FROM \`${tables.login}\`
            WHERE (\`account_id\` = ${esc(accountId)}
                AND \`web_auth_token\` = ${esc(authToken)}
                AND \`web_auth_token_enabled\` = '1')
            `
            const results = await DBConn.query(query);

            return results.length > 0;

        } catch (error) {
            console.error(error);
            return false;
        }
    }

    /**
     * Check if user is guildmaster of given guild in request
     * @param req Request object
     * @returns User is guildmaster
     */
    static async isGuildMaster(req: Request) {
        const body = req.body || {};
        
        const accountId = body["AID"];
        const guildId = body['GDID'];

        if (!accountId || !guildId) {
            return false;
        }

        try {
            const query = `
                SELECT account_id
                FROM \`${tables.guild}\` LEFT JOIN \`${tables.char}\` using (char_id)
                WHERE (\`${tables.char}\`.\`account_id\` = ${esc(accountId)}
                    AND \`${tables.guild}\`.\`guild_id\` = ${esc(guildId)})
                LIMIT 1
            `;
            const results = await DBConn.query(query);

            return results.length > 0;
        } catch(error) {
            console.error(error);
        }
    }
}